data_config:
  dataset_config:
    data_path: "ABSOLUTE_PATH_TO_MODEL_PREDICTIONS_FOLDER # E.g. /home/robustness_benchmark/multipathPP/predictions/"
  dataloader_config:
    num_workers: 8
output_config:
  out_path: "ABSOLUTE_PATH_TO_MODEL_EVALUATIONS_FOLDER # E.g. /home/robustness_benchmark/multipathPP/evaluations/"
model:
  name: "final_RoP_Cov_Single_lr4e-4__65c803f"